create table CATEGORIA(

CODIGO_CATEGORIA INT not null primary key,
DESCRICAO_CATEGORIA VARCHAR (50) not null unique

);


create table PRODUTO(

CODIGO_PRODUTO INT not null primary key,
DESCRICAO_PRODUTO VARCHAR (150) not null,
CODIGO_CATEGORIA INT not null,
FOREIGN KEY(CODIGO_CATEGORIA) REFERENCES CATEGORIA (CODIGO_CATEGORIA)
);



create table LOTE(

CODIGO_PRODUTO INT not null,
CODIGO_LOTE VARCHAR (10) not null,
VALIDADE DATE null,
DATA_FABRICACAO DATE not null,
PRIMARY KEY (CODIGO_PRODUTO, CODIGO_LOTE),
FOREIGN KEY(CODIGO_PRODUTO) REFERENCES PRODUTO (CODIGO_PRODUTO)

);



create table cliente(

CODIGO_CLIENTE INT not null primary key,
NOME_CLIENTE VARCHAR (150) not null,
CPF VARCHAR (11) null,
CNPJ VARCHAR (15)null

);




create table ENDERECO(

CODIGO_ENDERECO INT not null PRIMARY KEY,
CEP VARCHAR (8) not null,
CIDADE VARCHAR (30) not null,
ESTADO VARCHAR (30) not null,
LOGRADOURO VARCHAR (50) not null,
BAIRRO VARCHAR (30) not null,
NUMERO INT not null,
COMPLEMENTO VARCHAR (50) NULL
);

create table CLIENTE_ENDERECO(

CODIGO_CLIENTE INT not null,
CODIGO_ENDERECO INT not null,
DESCRICAO_ENDERECO VARCHAR (50) null,
PRIMARY KEY(CODIGO_CLIENTE, CODIGO_ENDERECO),
FOREIGN KEY(CODIGO_ENDERECO) REFERENCES ENDERECO (CODIGO_ENDERECO)


);



create table TELEFONE(

CODIGO_TELEFONE INT not null primary key,
DDD VARCHAR (3) not null,
NUMERO_TELEFONE VARCHAR (10) not null,
CELULAR BIT not null

);
 


create table TELEFONE_CLIENTE(

CODIGO_CLIENTE INT not null,
CODIGO_TELEFONE INT not null  ,
DESCRICAO_TELEFONE VARCHAR (50) null,
PRIMARY KEY (CODIGO_CLIENTE, CODIGO_TELEFONE),
FOREIGN KEY(CODIGO_TELEFONE) REFERENCES TELEFONE (CODIGO_TELEFONE),
FOREIGN KEY(CODIGO_CLIENTE) REFERENCES CLIENTE (CODIGO_CLIENTE)

);



create table LOJAS(

CODIGO_LOJA INT not null primary key,
NOME_LOJA VARCHAR (50) not null,
CODIGO_ENDERECO INT not null,
CNPJ VARCHAR (15) not null unique,
FOREIGN KEY(CODIGO_ENDERECO) REFERENCES ENDERECO (CODIGO_ENDERECO)

);




create table TELEFONE_LOJA(

CODIGO_LOJA INT not null ,
CODIGO_TELEFONE INT not null ,
DESCRICAO_TELEFONE VARCHAR (50) null,
PRIMARY KEY(CODIGO_LOJA, CODIGO_TELEFONE),
FOREIGN KEY(CODIGO_LOJA) REFERENCES LOJAS (CODIGO_LOJA),
FOREIGN KEY(CODIGO_TELEFONE) REFERENCES TELEFONE (CODIGO_TELEFONE)
);


create table PEDIDO(

CODIGO_PEDIDO INT not null primary key,
CODIGO_CLIENTE INT not null,
DATA_HORA_PEDIDO DATETIME not null,
FOREIGN KEY(CODIGO_CLIENTE) REFERENCES CLIENTE (CODIGO_CLIENTE),
EH_PEDIDO_WEB BIT NOT NULL
);



create table PEDIDO_ITENS(

NUMERO_PEDIDO INT not null,
CODIGO_PEDIDO INT not null ,
NUMERO_ITEM smallint not null,
CODIGO_PRODUTO INT not null,
VALOR_UNITARIO DECIMAL (8,3) not null,
QUANTIDADE_ITEM smallint not null,
DESCONTO DECIMAL (8,2) not null,
VALOR_TOTAL DECIMAL (8,2) not null,

primary key (CODIGO_PRODUTO, NUMERO_PEDIDO),
FOREIGN KEY(CODIGO_PEDIDO) REFERENCES PEDIDO (CODIGO_PEDIDO),
FOREIGN KEY(CODIGO_PRODUTO) REFERENCES PRODUTO (CODIGO_PRODUTO)
);




create table NUMERO_SERIE(
CODIGO_SERIE tinyint not null primary KEY, 
DESCRICAO_SERIE VARCHAR (50) not null unique
);




create table NF_CABECALHO(

NUMERO_NF INT not null primary KEY,
CHAVE_ACESSO INT not null UNIQUE,
CODIGO_SERIE tinyint not null,
DATA_EMISSAO DATE not null,
DESCONTO_TOTAL DECIMAL (8,2) not null,
VALOR_TOTAL DECIMAL (10,2) not null,
CODIGO_LOJA_EMISSOR INT not null,
CODIGO_CLIENTE_DESTINATARIO INT not null,
INDENTIFICACAO_NOTA BIT not null,
FOREIGN KEY(CODIGO_SERIE) REFERENCES NUMERO_SERIE (CODIGO_SERIE),
FOREIGN KEY(CODIGO_LOJA_EMISSOR) REFERENCES LOJAS (CODIGO_LOJA),
FOREIGN KEY(CODIGO_CLIENTE_DESTINATARIO) REFERENCES CLIENTE (CODIGO_CLIENTE)
);



create table NF_ITEM(
DATA_COMPRA DATE not null,
NUMERO_NF INT not null ,
CODIGO_PEDIDO INT not null,
NUMERO_ITEM_NF INT not null ,
CODIGO_PRODUTO INT not null,
VALOR_UNITARIO DECIMAL (8,3) not null,
DESCONTO_UNITARIO DECIMAL (8,3) not null,
VALOR_TOTAL DECIMAL (8,3) not null,
QUANTIDADE INT not null,
PERCENTUAL_ICMS DECIMAL (7,4) not null,
primary key ( numero_item_nf, NUMERO_NF),
FOREIGN KEY(CODIGO_PEDIDO) REFERENCES PEDIDO (CODIGO_PEDIDO),
FOREIGN KEY(CODIGO_PRODUTO) REFERENCES PRODUTO (CODIGO_PRODUTO)

);


show tables ;

